### ISSUE TITLE
Is minimum FB2K version really 1.4?

### ISSUE THREAD

**Issue by kbuffington** [marc2k3/foo_jscript_panel#13]
The 1.4 SDK is backwards compatible to 1.3 FB2K according to Peter (https://www.foobar2000.org/SDK)

Should the minimum version the component requires really be 1.4?

**Comment by marc2k3** [comment]
1) Peter provided the option in the SDK headers to make it 1.4 only. It's not like any dirty hacks are involved.
2) This component supported edge styles in default UI but that has changed in 1.4 due to the new splitters that were introduced which have their own edge options which override components. I now disable the combo box in default UI without having to consider the version.
3) Because the component is dynamically linked, it saves aggro telling people they must install C++ runtimes if running 1.3. I've seen so many people bitching about this over on HA - it's pathetic. They already have a windows folder containing 15-20GB worth of microsoft DLLs and they're crying over another few megabytes. v1.4 supplies the runtimes so it just works.
