### ISSUE TITLE
plman.IsAutoPlaylist(idx) with a unexisting playlist idx crash foobar

### ISSUE THREAD

**Issue by Ottodix** [marc2k3/foo_jscript_panel#22]
Hi,

The title say it all. if in your code you execute plman.IsAutoPlaylist(idx) and idx isn't equal to an existing playlist idx (so idx = -1, or idx >= plman.playlistCount), then the whole foobar application will crash.
There is the same issue with plman.IsPlaylistLocked(idx).

**Comment by marc2k3** [comment]
It looks like I broke this a few months ago because it used to be inside a try/catch statement but I removed it because it seemed OK with the script engine set to Chakra. I didn't realise it crashed with the JScript engine - I guess you must be running XP or WINE??

Anyway, this will be fixed in the next update.

**Comment by marc2k3** [comment]
I've uploaded a fixed version that now throws a script error.

https://github.com/marc2k3/foo_jscript_panel/releases
