### ISSUE TITLE
utils.CheckFont return false for fonts loaded by foo_ui_hacks

### ISSUE THREAD

**Issue by cerbaire** [marc2k3/foo_jscript_panel#24]
I installed foo_ui_hacks component, and configure it to load fonts from the fonts folder in my portable foobar2000 installation.
When going to UIHacks settings, it says that 3 TTF fonts has been loaded.

But when I call utils.CheckFont("guifx v2 transports"), it returns false.

**Comment by marc2k3** [comment]
Indeed. That because it's queries windows for the fonts that are actually installed. It has no idea of the trickery being performed by UI hacks,

But since you're using UI hacks, you have no reason to check for the font - you know it's going to be present on any portable setup???

If you really must, you can check with `gdi.Font` which returns null for fonts it can't load...

```js
console.log(gdi.Font("Guifx v2 Transports", 12) !== null);
```

The above returns `true` even when `utils.CheckFont` returns `false`.

**Comment by cerbaire** [comment]
Thanks marc2k3. It works.

**Comment by marc2k3** [comment]
interfaces.txt updated: https://github.com/marc2k3/foo_jscript_panel/commit/0b87078bb8d456366d5c1a8ed0c846629e82750e
