### ISSUE TITLE
[BUG] window.SetTimeout/window.SetInterval fails if there are 16 active timers

### ISSUE THREAD

**Issue by TheQwertiest** [marc2k3/foo_jscript_panel#3]
Repro steps:
```
for (var i = 0; i <64; i++) {
    var id = window.SetTimeout(function() {
    }, 1000);
    console.log(i, id > 0 ? 'Success' : 'Fail');
}
```
Result: only the first 16 calls are successful.

Cause:
SetInterval and SetTimout are implemented using timeSetEvent, which supports only 16 simultaneously running timers in one process (e.g. it counts timers from all JScript panels towards the limit). So when timers are exhausted, timeSetEvent fails and return zero, which causes SetInterval and SetTimout calls to fail as well.

timeSetEvent is declared deprecated by Miscrosoft and [CreateTimerQueue](https://msdn.microsoft.com/library/windows/desktop/ms682483.aspx) and [CreateTimerQueueTimer](https://msdn.microsoft.com/library/windows/desktop/ms682485.aspx) are suggested as a replacement.

For now I'm reimplementing [HostTimerDispatcher](foo_jscript_panel/src/host_timer_dispatcher.h) locally. I can make a Pull Request once I'm finished, if you are interested.

**Comment by marc2k3** [comment]
I'm leaning towards leaving the original code as it is. It's been around in WSH panel mod for 9 years and JScript Panel for the last 2 without anyone else running in to this limitation (at least not publicly on the HA forums).

Of course the real reason is that I'm totally incompetent and wouldn't be able to critically evaluate any PR!

**Comment by smoralis** [comment]
For what its worth I also noticed this limitation, which at first I thought I was some bad coding on my side.
Thanks for finding the cause of this limitation.
I noticed that JSsmooth browser  when adding new items to the Library , the refresh timer would lock making it visible that something was going wrong.
Due to the fact that Wilb's Bio and YTTM use a massive amount of timers ,along with Bretts smooth scripts , it is easy to reach this limitation and not know where exactly a script is failing.
I had to reduced my selected scripts to a minimum.

**Comment by Wil-B** [comment]
I have been plagued with this timer issue problem. Incidentally falstaff reported issues with it years ago. I never posted about it because I thought marc wouldn't be able to fix it. Wherever possible my scripts have a fallback for if the timer fails to set. Sometimes timers make things a lot nicer, but aren't necessarily esssential. For example, with smooth scrolling, if the timer fails to set, you can just scroll normally. Its simple to test if timers fail to set, using timer === 0. But where timers are essential, then things just fail. For me this has been the biggest bug in wsh / JScript panels and one of the first things I check if things are behaving strangely. Now with scripts having plenty of timers (e.g. jsplaylist-mod has at least 28 timers) it would be good to get it properly fixed, if possible, now the exact cause has been identified.

**Comment by TheQwertiest** [comment]
Everyone is welcome to test the changes in PR and/or critique the code =)

**Comment by marc2k3** [comment]
Thanks.

Here's a compiled DLL for testing...

https://github.com/marc2k3/foo_jscript_panel/wiki/foo_jscript_panel.dll

**Comment by marc2k3** [comment]
The above file has been updated with the latest commit pushed by @TheQwertiest just now.

**Comment by marc2k3** [comment]
@smoralis @Wil-B 

Here's a build from the latest update for testing. Thanks to @TheQwertiest 

https://github.com/marc2k3/foo_jscript_panel/wiki/foo_jscript_panel.dll

**Comment by Wil-B** [comment]
^ In 8 hours of testing it's all be fine. All timers have worked & I didn't spot any other issues. This has included testing on dui & cui layouts with many JScript panels where timers were clearly failing with v2.0.0 but working with the new test version.

**Comment by marc2k3** [comment]
v2.0.1-Beta1 is out.

https://github.com/marc2k3/foo_jscript_panel/releases
