### ISSUE TITLE
Image.Dispose() does not free handle to image

### ISSUE THREAD

**Issue by kbuffington** [marc2k3/foo_jscript_panel#44]
In my theme's `on_load_image_done`, I take the image and pass it to an art_cache which does the following:

    art_cache[path] = img.Resize(w, h);
    img.Dispose();

This allowed me to overwrite the actual image.jpg in the folder without stopping playback or anything else. Now when I attempt this I get a message saying that my Image saving program cannot access the file because it's being used by another process.

Presumably img.Dispose() is not actually freeing the file handle. The only way I can overwrite the saved image right now is to shut foobar down, which obviously isn't ideal :)

I just verified that this issue does not happen in 2.2.2, but does in 2.2.2.2 and 2.2.2.3. I don't have a copy of 2.2.2.1 to test.

**Comment by marc2k3** [comment]
First of all, Dispose doesn't have anything to do with file handles, it just frees the memory (I think! :P)

Also, I last made changes to this code in `v2.1.7.1` so there really shouldn't be any difference between any 2.2.x versions??? :confused: 

It should be unlocked immediately because I know you can delete the file immediately via Explorer but there does seem to be a lock in place when trying to overwrite it in place. I'll have to dig deeper.

**Comment by marc2k3** [comment]
Can you test this build?

[foo_jscript_panel.zip](https://github.com/marc2k3/foo_jscript_panel/files/3519408/foo_jscript_panel.zip)

**Comment by MojoBass** [comment]
Hello Marc,

I guess you have sent that build to be tested with eole (as I just posted an issue on HA).

Unfortunately no change after installation. 

Anything else I should have adopted except just installing the component and testing that?

Best regards,

MojoBass

 �

**Comment by marc2k3** [comment]
@MojoBass , nope Eole is built with Spider Monkey panel and the issue is very different to what's going on here with JScript Panel.

@kbuffington , I don't think there is anything I can do about the memory problem I encountered trying a different method. I think you'll have to dispose ALL references including your cache entry before overwriting the file. It's such a rare use case anyway - most people will keep their original files if resizing and generating new cache files where this wouldn't be an issue.

**Comment by kbuffington** [comment]
I think my use case probably wasn't as clear, so this complete config shows it in a super pedantic way:

```
function on_size() {
    if (window.Width && window.Height) {
        gdi.LoadImageAsync(window.ID, "C:\\Temp\\folder.jpg");
    }
}

function on_load_image_done(cookie, image) {
    try {
        console.log('on_load_image_done returned');
        image.Dispose();
    } catch(e) {
        console.log('error:',e);
    }
}
```
I can't copy over `C:\Temp\folder.jpg` until I shut down foobar now.

I have a feeling it's an SDK issue since if you haven't touched the image code I don't know what else it could be. If you have a copy of 2.2.2.1 I can verify that the issue occurred there which would strongly point to the SDK being the culprit and then I can raise an issue with Peter.

**Comment by marc2k3** [comment]
It won't be fb2k SDK related because it's using windows APIs. Anyway, try this instead...

[foo_jscript_panel.zip](https://github.com/marc2k3/foo_jscript_panel/files/3525304/foo_jscript_panel.zip)

**Comment by kbuffington** [comment]
Haha, I was falling asleep last night and suddenly realized that of course it wouldn't have anything to do with the SDK since I'm not even using the AlbumArt methods.

Anyway, that fixed the issue. Can happily overwrite once `img.Dispose` has been called.

**Comment by marc2k3** [comment]
I have to confess... you were right about this changing since `v2.2.2`. I forgot about the changes which were made to be compatible with the latest version of VS2019. Although it compiled and displayed images fine, it didn't release them properly. :disappointed:

**Comment by marc2k3** [comment]
Here's a proper release with the fix...

https://github.com/marc2k3/foo_jscript_panel/releases
